CREATE TABLE `alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alertNumber` varchar(32) NOT NULL,
	`type` enum('low_stock','shortage','late_shipment','yield_variance','expiring_lot','quality_issue','po_overdue','reconciliation_variance') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'warning',
	`status` enum('open','acknowledged','in_progress','resolved','dismissed') NOT NULL DEFAULT 'open',
	`title` varchar(255) NOT NULL,
	`description` text,
	`entityType` varchar(64),
	`entityId` int,
	`thresholdValue` decimal(15,4),
	`actualValue` decimal(15,4),
	`assignedTo` int,
	`acknowledgedBy` int,
	`acknowledgedAt` timestamp,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolutionNotes` text,
	`autoGenerated` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryAllocations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`channel` enum('shopify','amazon','wholesale','retail','other') NOT NULL DEFAULT 'shopify',
	`storeId` int,
	`productId` int NOT NULL,
	`warehouseId` int NOT NULL,
	`allocatedQuantity` decimal(15,4) NOT NULL,
	`remainingQuantity` decimal(15,4) NOT NULL,
	`unit` varchar(32) DEFAULT 'EA',
	`lastSyncedToChannel` timestamp,
	`channelReportedQuantity` decimal(15,4),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryAllocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryBalances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lotId` int NOT NULL,
	`productId` int NOT NULL,
	`warehouseId` int NOT NULL,
	`zoneId` varchar(64),
	`binId` varchar(64),
	`status` enum('available','hold','reserved','quarantine','damaged') NOT NULL DEFAULT 'available',
	`quantity` decimal(15,4) NOT NULL DEFAULT '0',
	`unit` varchar(32) NOT NULL DEFAULT 'EA',
	`lastCountDate` timestamp,
	`lastCountQuantity` decimal(15,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryBalances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryLots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lotCode` varchar(64) NOT NULL,
	`productId` int NOT NULL,
	`productType` enum('finished','wip','material','packaging','subassembly') NOT NULL DEFAULT 'finished',
	`expiryDate` timestamp,
	`manufactureDate` timestamp,
	`attributes` json,
	`sourceType` enum('production','purchase','transfer','adjustment','opening') NOT NULL DEFAULT 'purchase',
	`sourceReferenceId` int,
	`status` enum('active','expired','consumed','quarantine') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryLots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryReservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`salesOrderId` int NOT NULL,
	`salesOrderLineId` int NOT NULL,
	`lotId` int,
	`productId` int NOT NULL,
	`warehouseId` int NOT NULL,
	`reservedQuantity` decimal(15,4) NOT NULL,
	`fulfilledQuantity` decimal(15,4) DEFAULT '0',
	`releasedQuantity` decimal(15,4) DEFAULT '0',
	`unit` varchar(32) DEFAULT 'EA',
	`status` enum('reserved','partial_fulfilled','fulfilled','released','cancelled') NOT NULL DEFAULT 'reserved',
	`reservedAt` timestamp NOT NULL DEFAULT (now()),
	`fulfilledAt` timestamp,
	`releasedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryReservations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventoryTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionNumber` varchar(64) NOT NULL,
	`transactionType` enum('receive','consume','adjust','transfer_in','transfer_out','reserve','release','ship','return','scrap','count_adjust') NOT NULL,
	`lotId` int,
	`productId` int NOT NULL,
	`fromWarehouseId` int,
	`toWarehouseId` int,
	`fromStatus` enum('available','hold','reserved','quarantine','damaged'),
	`toStatus` enum('available','hold','reserved','quarantine','damaged'),
	`quantity` decimal(15,4) NOT NULL,
	`unit` varchar(32) NOT NULL DEFAULT 'EA',
	`previousBalance` decimal(15,4),
	`newBalance` decimal(15,4),
	`referenceType` varchar(64),
	`referenceId` int,
	`reason` text,
	`performedBy` int,
	`performedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `inventoryTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alertId` int,
	`type` enum('create_po','create_work_order','transfer_inventory','adjust_forecast','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`actionPayload` json,
	`status` enum('pending','approved','rejected','executed') NOT NULL DEFAULT 'pending',
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`aiGenerated` boolean DEFAULT true,
	`aiRationale` text,
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectedBy` int,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`executedAt` timestamp,
	`executionResult` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reconciliationLines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int NOT NULL,
	`productId` int NOT NULL,
	`sku` varchar(64),
	`warehouseId` int,
	`erpQuantity` decimal(15,4) NOT NULL,
	`channelQuantity` decimal(15,4) NOT NULL,
	`deltaQuantity` decimal(15,4) NOT NULL,
	`variancePercent` decimal(8,2),
	`status` enum('pass','warning','critical') NOT NULL DEFAULT 'pass',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reconciliationLines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reconciliationRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runNumber` varchar(32) NOT NULL,
	`type` enum('scheduled','manual') NOT NULL DEFAULT 'scheduled',
	`channel` enum('shopify','amazon','all') NOT NULL DEFAULT 'shopify',
	`storeId` int,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`totalSkus` int DEFAULT 0,
	`passedSkus` int DEFAULT 0,
	`warningSkus` int DEFAULT 0,
	`criticalSkus` int DEFAULT 0,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`initiatedBy` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reconciliationRuns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salesEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` enum('shopify','amazon','manual','other') NOT NULL DEFAULT 'shopify',
	`eventType` enum('order_created','order_fulfilled','order_cancelled','order_refunded') NOT NULL,
	`shopifyOrderId` varchar(64),
	`shopifyFulfillmentId` varchar(64),
	`salesOrderId` int,
	`allocationId` int,
	`productId` int,
	`quantity` decimal(15,4),
	`eventData` json,
	`processedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `salesEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salesOrderLines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`salesOrderId` int NOT NULL,
	`productId` int NOT NULL,
	`shopifyLineItemId` varchar(64),
	`sku` varchar(64),
	`name` varchar(255),
	`quantity` decimal(15,4) NOT NULL,
	`fulfilledQuantity` decimal(15,4) DEFAULT '0',
	`unitPrice` decimal(15,2) NOT NULL,
	`totalPrice` decimal(15,2) NOT NULL,
	`unit` varchar(32) DEFAULT 'EA',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `salesOrderLines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salesOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(64) NOT NULL,
	`source` enum('shopify','manual','api','other') NOT NULL DEFAULT 'manual',
	`shopifyOrderId` varchar(64),
	`shopifyOrderNumber` varchar(64),
	`customerId` int,
	`status` enum('pending','confirmed','processing','shipped','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`fulfillmentStatus` enum('unfulfilled','partial','fulfilled') NOT NULL DEFAULT 'unfulfilled',
	`paymentStatus` enum('pending','paid','partial','refunded') NOT NULL DEFAULT 'pending',
	`subtotal` decimal(15,2) DEFAULT '0',
	`taxAmount` decimal(15,2) DEFAULT '0',
	`shippingAmount` decimal(15,2) DEFAULT '0',
	`discountAmount` decimal(15,2) DEFAULT '0',
	`totalAmount` decimal(15,2) DEFAULT '0',
	`currency` varchar(3) DEFAULT 'USD',
	`shippingAddress` json,
	`billingAddress` json,
	`notes` text,
	`orderDate` timestamp NOT NULL DEFAULT (now()),
	`shippedAt` timestamp,
	`deliveredAt` timestamp,
	`cancelledAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `salesOrders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopifyLocationMappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`shopifyLocationId` varchar(64) NOT NULL,
	`shopifyLocationName` varchar(255),
	`warehouseId` int NOT NULL,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopifyLocationMappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopifySkuMappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeId` int NOT NULL,
	`shopifyProductId` varchar(64) NOT NULL,
	`shopifyVariantId` varchar(64) NOT NULL,
	`shopifySku` varchar(128),
	`productId` int NOT NULL,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopifySkuMappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shopifyStores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`storeDomain` varchar(255) NOT NULL,
	`storeName` varchar(255),
	`accessToken` text,
	`apiVersion` varchar(16) DEFAULT '2024-01',
	`isEnabled` boolean DEFAULT true,
	`syncInventory` boolean DEFAULT true,
	`syncOrders` boolean DEFAULT true,
	`inventoryAuthority` enum('erp','shopify','hybrid') DEFAULT 'hybrid',
	`lastSyncAt` timestamp,
	`webhookSecret` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopifyStores_id` PRIMARY KEY(`id`),
	CONSTRAINT `shopifyStores_storeDomain_unique` UNIQUE(`storeDomain`)
);
--> statement-breakpoint
CREATE TABLE `webhookEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` enum('shopify','quickbooks','hubspot','stripe','other') NOT NULL DEFAULT 'shopify',
	`topic` varchar(128) NOT NULL,
	`idempotencyKey` varchar(255) NOT NULL,
	`payload` json,
	`status` enum('received','processing','processed','failed','ignored') NOT NULL DEFAULT 'received',
	`errorMessage` text,
	`retryCount` int DEFAULT 0,
	`processedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `webhookEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workOrderOutputs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workOrderId` int NOT NULL,
	`lotId` int NOT NULL,
	`productId` int NOT NULL,
	`quantity` decimal(15,4) NOT NULL,
	`unit` varchar(32) NOT NULL DEFAULT 'EA',
	`yieldPercent` decimal(8,2),
	`qualityGrade` enum('A','B','C','reject') DEFAULT 'A',
	`warehouseId` int,
	`notes` text,
	`producedAt` timestamp NOT NULL DEFAULT (now()),
	`producedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `workOrderOutputs_id` PRIMARY KEY(`id`)
);
