CREATE TABLE `email_attachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`emailId` int NOT NULL,
	`filename` varchar(255) NOT NULL,
	`mimeType` varchar(100),
	`size` int,
	`storageUrl` varchar(512),
	`storageKey` varchar(255),
	`isProcessed` boolean DEFAULT false,
	`extractedText` text,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `email_attachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inbound_emails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`messageId` varchar(255),
	`fromEmail` varchar(255) NOT NULL,
	`fromName` varchar(255),
	`toEmail` varchar(255) NOT NULL,
	`subject` varchar(500),
	`bodyText` text,
	`bodyHtml` text,
	`receivedAt` timestamp NOT NULL,
	`email_parsing_status` enum('pending','processing','parsed','failed','reviewed','archived') NOT NULL DEFAULT 'pending',
	`parsedAt` timestamp,
	`errorMessage` text,
	`rawHeaders` json,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inbound_emails_id` PRIMARY KEY(`id`),
	CONSTRAINT `inbound_emails_messageId_unique` UNIQUE(`messageId`)
);
--> statement-breakpoint
CREATE TABLE `parsed_document_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentId` int NOT NULL,
	`lineNumber` int DEFAULT 1,
	`description` varchar(500),
	`sku` varchar(100),
	`quantity` decimal(12,4),
	`unit` varchar(50),
	`unitPrice` decimal(12,4),
	`totalPrice` decimal(12,2),
	`productId` int,
	`rawMaterialId` int,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `parsed_document_line_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `parsed_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`emailId` int,
	`attachmentId` int,
	`parsed_document_type` enum('receipt','invoice','purchase_order','bill_of_lading','packing_list','customs_document','freight_quote','shipping_label','other') NOT NULL,
	`confidence` decimal(5,2),
	`vendorName` varchar(255),
	`vendorEmail` varchar(255),
	`vendorId` int,
	`documentNumber` varchar(100),
	`documentDate` timestamp,
	`dueDate` timestamp,
	`subtotal` decimal(12,2),
	`taxAmount` decimal(12,2),
	`shippingAmount` decimal(12,2),
	`totalAmount` decimal(12,2),
	`currency` varchar(3) DEFAULT 'USD',
	`trackingNumber` varchar(100),
	`carrierName` varchar(255),
	`shipmentId` int,
	`purchaseOrderId` int,
	`lineItems` json,
	`isReviewed` boolean DEFAULT false,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`isApproved` boolean DEFAULT false,
	`createdTransactionId` int,
	`createdVendorId` int,
	`rawExtractedData` json,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parsed_documents_id` PRIMARY KEY(`id`)
);
