CREATE TABLE `emailCredentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`provider` enum('gmail','outlook','yahoo','icloud','custom') NOT NULL,
	`email` varchar(320) NOT NULL,
	`imapHost` varchar(255),
	`imapPort` int DEFAULT 993,
	`imapSecure` boolean DEFAULT true,
	`imapUsername` varchar(255),
	`imapPassword` text,
	`accessToken` text,
	`refreshToken` text,
	`tokenExpiresAt` timestamp,
	`scanFolder` varchar(255) DEFAULT 'INBOX',
	`scanUnreadOnly` boolean DEFAULT true,
	`markAsRead` boolean DEFAULT false,
	`maxEmailsPerScan` int DEFAULT 50,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastScanAt` timestamp,
	`lastScanStatus` enum('success','failed','partial'),
	`lastScanError` text,
	`emailsScanned` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emailCredentials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `emailScanLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`credentialId` int NOT NULL,
	`scheduledScanId` int,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`status` enum('running','success','failed','partial') NOT NULL DEFAULT 'running',
	`emailsFound` int DEFAULT 0,
	`emailsProcessed` int DEFAULT 0,
	`emailsCategorized` int DEFAULT 0,
	`errorMessage` text,
	`details` text,
	CONSTRAINT `emailScanLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduledEmailScans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`credentialId` int NOT NULL,
	`companyId` int,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`intervalMinutes` int NOT NULL DEFAULT 15,
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`lastRunStatus` enum('success','failed','running'),
	`lastRunError` text,
	`lastRunEmailsFound` int DEFAULT 0,
	`totalRuns` int DEFAULT 0,
	`totalEmailsProcessed` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduledEmailScans_id` PRIMARY KEY(`id`)
);
