CREATE TABLE `customsClearances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clearanceNumber` varchar(50) NOT NULL,
	`shipmentId` int,
	`rfqId` int,
	`type` enum('import','export') NOT NULL,
	`status` enum('pending_documents','documents_submitted','under_review','additional_info_required','cleared','held','rejected') NOT NULL DEFAULT 'pending_documents',
	`customsOffice` varchar(255),
	`portOfEntry` varchar(255),
	`country` varchar(100),
	`customsBrokerId` int,
	`brokerReference` varchar(100),
	`submissionDate` timestamp,
	`expectedClearanceDate` timestamp,
	`actualClearanceDate` timestamp,
	`dutyAmount` decimal(15,2),
	`taxAmount` decimal(15,2),
	`otherFees` decimal(15,2),
	`totalAmount` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`hsCode` varchar(20),
	`countryOfOrigin` varchar(100),
	`certificateOfOrigin` boolean DEFAULT false,
	`notes` text,
	`aiSummary` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customsClearances_id` PRIMARY KEY(`id`),
	CONSTRAINT `customsClearances_clearanceNumber_unique` UNIQUE(`clearanceNumber`)
);
--> statement-breakpoint
CREATE TABLE `customsDocuments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clearanceId` int NOT NULL,
	`documentType` enum('commercial_invoice','packing_list','bill_of_lading','airway_bill','certificate_of_origin','customs_declaration','import_license','export_license','insurance_certificate','inspection_certificate','phytosanitary_certificate','fumigation_certificate','dangerous_goods_declaration','other') NOT NULL,
	`name` varchar(255) NOT NULL,
	`fileUrl` text,
	`fileKey` varchar(500),
	`mimeType` varchar(100),
	`fileSize` int,
	`status` enum('pending','uploaded','verified','rejected','expired') DEFAULT 'pending',
	`expiryDate` timestamp,
	`verifiedAt` timestamp,
	`verifiedById` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customsDocuments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `freightBookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingNumber` varchar(50) NOT NULL,
	`quoteId` int NOT NULL,
	`rfqId` int NOT NULL,
	`carrierId` int NOT NULL,
	`status` enum('pending','confirmed','in_transit','arrived','delivered','cancelled') NOT NULL DEFAULT 'pending',
	`trackingNumber` varchar(100),
	`containerNumber` varchar(50),
	`vesselName` varchar(255),
	`voyageNumber` varchar(50),
	`bookingDate` timestamp,
	`pickupDate` timestamp,
	`departureDate` timestamp,
	`arrivalDate` timestamp,
	`deliveryDate` timestamp,
	`agreedCost` decimal(15,2),
	`actualCost` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightBookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `freightBookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `freightCarriers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('ocean','air','ground','rail','multimodal') NOT NULL,
	`contactName` varchar(255),
	`email` varchar(320),
	`phone` varchar(32),
	`address` text,
	`country` varchar(100),
	`website` varchar(500),
	`notes` text,
	`rating` int,
	`isPreferred` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightCarriers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `freightEmails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqId` int,
	`carrierId` int,
	`direction` enum('outbound','inbound') NOT NULL,
	`emailType` enum('rfq_request','quote_response','follow_up','clarification','booking_confirmation','document_request','customs_update','other') NOT NULL,
	`fromEmail` varchar(320),
	`toEmail` varchar(320),
	`ccEmails` text,
	`subject` varchar(500),
	`body` text,
	`htmlBody` text,
	`aiGenerated` boolean DEFAULT false,
	`aiParsed` boolean DEFAULT false,
	`aiExtractedData` text,
	`status` enum('draft','sent','delivered','read','replied','failed') DEFAULT 'draft',
	`sentAt` timestamp,
	`readAt` timestamp,
	`attachments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightEmails_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `freightQuotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqId` int NOT NULL,
	`carrierId` int NOT NULL,
	`quoteNumber` varchar(50),
	`status` enum('pending','received','under_review','accepted','rejected','expired') NOT NULL DEFAULT 'pending',
	`freightCost` decimal(15,2),
	`fuelSurcharge` decimal(15,2),
	`originCharges` decimal(15,2),
	`destinationCharges` decimal(15,2),
	`customsFees` decimal(15,2),
	`insuranceCost` decimal(15,2),
	`otherCharges` decimal(15,2),
	`totalCost` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`transitDays` int,
	`shippingMode` varchar(50),
	`routeDescription` text,
	`validUntil` timestamp,
	`aiScore` int,
	`aiAnalysis` text,
	`aiRecommendation` text,
	`receivedVia` enum('email','portal','phone','manual') DEFAULT 'email',
	`emailThreadId` varchar(255),
	`rawEmailContent` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightQuotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `freightRfqs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqNumber` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`status` enum('draft','sent','awaiting_quotes','quotes_received','awarded','cancelled') NOT NULL DEFAULT 'draft',
	`originCountry` varchar(100),
	`originCity` varchar(255),
	`originAddress` text,
	`destinationCountry` varchar(100),
	`destinationCity` varchar(255),
	`destinationAddress` text,
	`cargoDescription` text,
	`cargoType` enum('general','hazardous','refrigerated','oversized','fragile','liquid','bulk') DEFAULT 'general',
	`totalWeight` decimal(12,2),
	`totalVolume` decimal(12,2),
	`numberOfPackages` int,
	`dimensions` text,
	`hsCode` varchar(20),
	`declaredValue` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`preferredMode` enum('ocean_fcl','ocean_lcl','air','express','ground','rail','any') DEFAULT 'any',
	`incoterms` varchar(10),
	`requiredPickupDate` timestamp,
	`requiredDeliveryDate` timestamp,
	`insuranceRequired` boolean DEFAULT false,
	`customsClearanceRequired` boolean DEFAULT true,
	`purchaseOrderId` int,
	`vendorId` int,
	`notes` text,
	`createdById` int,
	`quoteDueDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightRfqs_id` PRIMARY KEY(`id`),
	CONSTRAINT `freightRfqs_rfqNumber_unique` UNIQUE(`rfqNumber`)
);
