CREATE TABLE `data_room_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`folderId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`fileType` varchar(64) NOT NULL,
	`mimeType` varchar(128),
	`fileSize` bigint,
	`pageCount` int,
	`storageType` enum('s3','google_drive') NOT NULL DEFAULT 's3',
	`storageUrl` varchar(512),
	`storageKey` varchar(255),
	`googleDriveFileId` varchar(255),
	`googleDriveWebViewLink` varchar(512),
	`thumbnailUrl` varchar(512),
	`sortOrder` int NOT NULL DEFAULT 0,
	`isHidden` boolean NOT NULL DEFAULT false,
	`version` int NOT NULL DEFAULT 1,
	`originalDocumentId` int,
	`uploadedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_room_folders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`parentId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`googleDriveFolderId` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_folders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_room_invitations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`email` varchar(320) NOT NULL,
	`name` varchar(255),
	`role` enum('viewer','editor','admin') NOT NULL DEFAULT 'viewer',
	`allowDownload` boolean NOT NULL DEFAULT true,
	`allowPrint` boolean NOT NULL DEFAULT true,
	`restrictedFolderIds` json,
	`restrictedDocumentIds` json,
	`inviteCode` varchar(64) NOT NULL,
	`status` enum('pending','accepted','declined','expired') NOT NULL DEFAULT 'pending',
	`expiresAt` timestamp,
	`acceptedAt` timestamp,
	`visitorId` int,
	`message` text,
	`invitedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_invitations_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_room_invitations_inviteCode_unique` UNIQUE(`inviteCode`)
);
--> statement-breakpoint
CREATE TABLE `data_room_links` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`linkCode` varchar(64) NOT NULL,
	`name` varchar(255),
	`password` varchar(255),
	`expiresAt` timestamp,
	`maxViews` int,
	`viewCount` int NOT NULL DEFAULT 0,
	`allowDownload` boolean NOT NULL DEFAULT true,
	`allowPrint` boolean NOT NULL DEFAULT true,
	`restrictedFolderIds` json,
	`restrictedDocumentIds` json,
	`requireEmail` boolean NOT NULL DEFAULT true,
	`requireName` boolean NOT NULL DEFAULT false,
	`requireCompany` boolean NOT NULL DEFAULT false,
	`requirePhone` boolean NOT NULL DEFAULT false,
	`customFields` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_links_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_room_links_linkCode_unique` UNIQUE(`linkCode`)
);
--> statement-breakpoint
CREATE TABLE `data_room_visitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`linkId` int,
	`email` varchar(320),
	`name` varchar(255),
	`company` varchar(255),
	`phone` varchar(32),
	`customFieldData` json,
	`ndaAcceptedAt` timestamp,
	`ndaIpAddress` varchar(45),
	`ipAddress` varchar(45),
	`userAgent` text,
	`referrer` varchar(512),
	`totalViews` int NOT NULL DEFAULT 0,
	`totalTimeSpent` int NOT NULL DEFAULT 0,
	`lastViewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_visitors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_rooms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`slug` varchar(128) NOT NULL,
	`ownerId` int NOT NULL,
	`isPublic` boolean NOT NULL DEFAULT false,
	`password` varchar(255),
	`requiresNda` boolean NOT NULL DEFAULT false,
	`ndaText` text,
	`logoUrl` varchar(512),
	`brandColor` varchar(7),
	`welcomeMessage` text,
	`allowDownload` boolean NOT NULL DEFAULT true,
	`allowPrint` boolean NOT NULL DEFAULT true,
	`expiresAt` timestamp,
	`watermarkEnabled` boolean NOT NULL DEFAULT false,
	`googleDriveFolderId` varchar(255),
	`lastSyncedAt` timestamp,
	`status` enum('active','archived','draft') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_rooms_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_rooms_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `document_views` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentId` int NOT NULL,
	`visitorId` int NOT NULL,
	`linkId` int,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`endedAt` timestamp,
	`duration` int,
	`pagesViewed` json,
	`totalPagesViewed` int NOT NULL DEFAULT 0,
	`percentViewed` decimal(5,2),
	`downloaded` boolean NOT NULL DEFAULT false,
	`downloadedAt` timestamp,
	`printed` boolean NOT NULL DEFAULT false,
	`deviceType` varchar(32),
	`browser` varchar(64),
	`os` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `document_views_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `imap_credentials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`host` varchar(255) NOT NULL,
	`port` int NOT NULL DEFAULT 993,
	`secure` boolean NOT NULL DEFAULT true,
	`email` varchar(320) NOT NULL,
	`encryptedPassword` text NOT NULL,
	`folder` varchar(128) NOT NULL DEFAULT 'INBOX',
	`unseenOnly` boolean NOT NULL DEFAULT true,
	`markAsSeen` boolean NOT NULL DEFAULT false,
	`pollingEnabled` boolean NOT NULL DEFAULT false,
	`pollingIntervalMinutes` int NOT NULL DEFAULT 15,
	`lastPolledAt` timestamp,
	`lastMessageUid` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastError` text,
	`lastSuccessAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `imap_credentials_id` PRIMARY KEY(`id`)
);
