CREATE TABLE `vendorQuotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqId` int NOT NULL,
	`vendorId` int NOT NULL,
	`quoteNumber` varchar(50),
	`status` enum('pending','received','under_review','accepted','rejected','expired','converted_to_po') NOT NULL DEFAULT 'pending',
	`unitPrice` decimal(15,4),
	`quantity` decimal(15,4),
	`totalPrice` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`shippingCost` decimal(15,2),
	`handlingFee` decimal(15,2),
	`taxAmount` decimal(15,2),
	`otherCharges` decimal(15,2),
	`totalWithCharges` decimal(15,2),
	`leadTimeDays` int,
	`estimatedDeliveryDate` timestamp,
	`minimumOrderQty` decimal(15,4),
	`validUntil` timestamp,
	`paymentTerms` varchar(100),
	`aiScore` int,
	`aiAnalysis` text,
	`aiRecommendation` text,
	`priceComparisonRank` int,
	`leadTimeComparisonRank` int,
	`overallRank` int,
	`receivedVia` enum('email','portal','phone','manual') DEFAULT 'email',
	`emailThreadId` varchar(255),
	`rawEmailContent` text,
	`attachments` text,
	`convertedToPOId` int,
	`convertedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorQuotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendorRfqEmails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqId` int,
	`vendorId` int,
	`quoteId` int,
	`direction` enum('outbound','inbound') NOT NULL,
	`emailType` enum('rfq_request','quote_response','follow_up','clarification','award_notification','rejection_notification','other') NOT NULL,
	`fromEmail` varchar(320),
	`toEmail` varchar(320),
	`ccEmails` text,
	`subject` varchar(500),
	`body` text,
	`htmlBody` text,
	`aiGenerated` boolean DEFAULT false,
	`aiParsed` boolean DEFAULT false,
	`aiExtractedData` text,
	`sendStatus` enum('draft','queued','sent','delivered','failed','bounced') DEFAULT 'draft',
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`openedAt` timestamp,
	`errorMessage` text,
	`externalMessageId` varchar(255),
	`threadId` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorRfqEmails_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendorRfqInvitations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqId` int NOT NULL,
	`vendorId` int NOT NULL,
	`status` enum('pending','sent','viewed','responded','declined','no_response') NOT NULL DEFAULT 'pending',
	`invitedAt` timestamp,
	`viewedAt` timestamp,
	`respondedAt` timestamp,
	`reminderSentAt` timestamp,
	`reminderCount` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorRfqInvitations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendorRfqs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rfqNumber` varchar(50) NOT NULL,
	`status` enum('draft','sent','partially_received','all_received','awarded','cancelled','expired') NOT NULL DEFAULT 'draft',
	`rawMaterialId` int,
	`materialName` varchar(255) NOT NULL,
	`materialDescription` text,
	`quantity` decimal(15,4) NOT NULL,
	`unit` varchar(50) NOT NULL,
	`specifications` text,
	`requiredDeliveryDate` timestamp,
	`deliveryLocation` varchar(255),
	`deliveryAddress` text,
	`incoterms` varchar(10),
	`quoteDueDate` timestamp,
	`validityPeriod` int,
	`purchaseRequestId` int,
	`projectId` int,
	`priority` enum('low','normal','high','urgent') DEFAULT 'normal',
	`notes` text,
	`internalNotes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorRfqs_id` PRIMARY KEY(`id`)
);
