CREATE TABLE `auto_reply_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email_category` enum('receipt','purchase_order','invoice','shipping_confirmation','freight_quote','delivery_notification','order_confirmation','payment_confirmation','general') NOT NULL DEFAULT 'general',
	`isEnabled` boolean NOT NULL DEFAULT true,
	`priority` int NOT NULL DEFAULT 0,
	`senderPattern` varchar(255),
	`subjectPattern` varchar(255),
	`bodyKeywords` json,
	`minConfidence` decimal(5,2) DEFAULT '0.7',
	`replyTemplate` text NOT NULL,
	`replySubjectPrefix` varchar(100) DEFAULT 'Re:',
	`tone` enum('professional','friendly','formal') DEFAULT 'professional',
	`includeOriginal` boolean DEFAULT true,
	`delayMinutes` int DEFAULT 0,
	`autoSend` boolean DEFAULT false,
	`createTask` boolean DEFAULT true,
	`notifyOwner` boolean DEFAULT false,
	`timesTriggered` int DEFAULT 0,
	`lastTriggeredAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `auto_reply_rules_id` PRIMARY KEY(`id`)
);
