CREATE TABLE `sent_emails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inboundEmailId` int,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`toEmail` varchar(255) NOT NULL,
	`toName` varchar(255),
	`fromEmail` varchar(255) NOT NULL,
	`fromName` varchar(255),
	`subject` varchar(500) NOT NULL,
	`bodyHtml` text,
	`bodyText` text,
	`status` enum('queued','sent','delivered','failed','bounced') NOT NULL DEFAULT 'queued',
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`errorMessage` text,
	`messageId` varchar(255),
	`threadId` varchar(255),
	`sentBy` int,
	`aiGenerated` boolean DEFAULT false,
	`aiTaskId` int,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sent_emails_id` PRIMARY KEY(`id`)
);
